### ISSUE TITLE
Database content different with the one from LibChecker-Rules repo

### ISSUE THREAD

**Issue by cliuff** [LibChecker/LibChecker-Rules-Bundle#21]
After running diff between the rules.db from rules repo and the one included in this library, I wonder why these differences exist?

![image](https://user-images.githubusercontent.com/35420834/229770772-29e51b0b-ca35-44f3-a11b-9456ccfb3494.png)

**Comment by zhaobozhen** [comment]
The database in the LibChecker-Rules repository is now relying on scripts to generate it, maybe the scripts are written a bit wrong, I'll keep an eye on it.

**Comment by zhaobozhen** [comment]
resolved in V32.
